### ISSUE TITLE
Apply class on stick

### ISSUE THREAD

**Issue by geirsagberg** [lucas-issa/react-sticky-hierarchical#1]
First of all, very good library, first one I found that does seamless stacking.

Is there any way to configure a CSS class that should be applied once an element becomes sticky?

**Comment by lucas-issa** [comment]
Hi @geirsagberg.
I just submitted a change that implements your suggestion.
Thanks for your feedback.

**Comment by geirsagberg** [comment]
Awesome, thanks a lot :-)
